'use strict'

module.exports = function(sequelize,DataTypes){
    return sequelize.define('Vip_basic',{
        id: {
            type:DataTypes.INTEGER(11),
            autoIncrement:true,
            primaryKey:true,
            unique:true
        },
        name: {
            type: DataTypes.STRING
        },
        phone: {
            type:DataTypes.STRING
        },
        gender:{
            type: DataTypes.STRING
        },
        birth:{
            type: DataTypes.DATE
        },
        qq:{
            type:DataTypes.STRING
        },
        portrait:{
            type:DataTypes.STRING
        },
        addr:{
            type:DataTypes.STRING
        },
        college:{
            type:DataTypes.STRING
        },
        major:{
            type:DataTypes.STRING
        },
        company:{
            type:DataTypes.STRING
        },
        job:{
            type:DataTypes.STRING
        },
        evaluate:{
            type:DataTypes.FLOAT,
            defaultValue:0.0
        },
        check_name:{
            type:DataTypes.INTEGER,
            defaultValue:1
        },
        check_phone:{
            type:DataTypes.INTEGER,
            defaultValue:1
        },
        check_birth:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_qq:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_portrait:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_addr:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_college:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_major:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_company:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_company:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        check_job:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        checked:{
            type:DataTypes.INTEGER,
            defaultValue:0
        },
        openid:{
            type:DataTypes.STRING
        },
        unionid:{
            type:DataTypes.STRING
        },
        submit_time:{
            type:DataTypes.DATE
        },
        check_time:{
            type:DataTypes.DATE
        },
        check_person:{
            type:DataTypes.STRING
        }
    },{
        timestamps:false,
        underscored:true,
        freezeTableName:true,
        tableName:'vip_basic',
        charset:'utf8',
        collate:'utf8_general_ci'
    })
}